### ISSUE TITLE
Is it possible to cancel axios requests?

### ISSUE THREAD

**Issue by paulwehner** [mzabriskie/axios#80] opened 2015-06-23 22:30 UTC
I'm building something similar to search lookahead, and with each change event to a text input I want to fire off a new set of axios get requests. When the change event occurs, I need to cancel all uncompleted axios requests from the last change event (as they will no longer be needed)... and fire of a new set of axios requests. Is this possible?

**Comment by paulwehner** [comment] 2015-06-23 23:11
I just saw this: https://github.com/mzabriskie/axios/issues/50. Hopefully this will be implemented soon!

**Comment by mzabriskie** [comment] 2015-06-23 23:25
@paulwehner I was actually working on this over the weekend. Should hopefully have something soon.

**Comment by paulwehner** [comment] 2015-06-24 06:34
Awesome. Thanks for responding.

**Comment by nelix** [comment] 2015-07-15 05:25
Did you make much progress with this @mzabriskie?

**Comment by mzabriskie** [comment] 2015-07-25 02:11
@nelix I have a working version. I am just debating a piece of the implementation. Should be released soon.

**Comment by paulwehner** [comment] 2015-09-13 12:03
Was this released? Is there documentation for this?

**Comment by mzabriskie** [comment] 2015-09-23 18:50
@paulwehner nothing has been released yet. I am very torn on the implementation. Looking at other possible solutions.

**Comment by mzabriskie** [comment] 2015-09-23 18:51
This is a duplicate of #50

**Closed by mzabriskie** 2015-09-23 18:51 UTC

**Comment by onlyongunz** [comment] 2017-01-14 15:22
Can anyone give a little example here?

Or on the example folder?

thankyou

**Comment by emartini** [comment] 2017-02-05 12:56
@onlyongunz ,  it's explained on the [readme](https://github.com/mzabriskie/axios#cancellation)

**Comment by challenger532** [comment] 2018-05-26 14:45
use [faxios](https://www.npmjs.com/package/faxios)

```js
// building..
let req = faxios()
  .baseURL("http://jsonplaceholder.typicode.com")
  .url("posts", 1, "comments")
 
// fetching..
req // => 
  .FETCH // => Promise
  .then(res => {})
  .catch(err => {});
 
// canceling...
req.cancel();
```

**Comment by AbhayShiro** [comment] 2020-05-04 10:44
https://www.npmjs.com/package/axios-cancel

Try this package. It helped me.

**Comment by jasonsaayman** [comment] 2020-05-05 11:56
This thread has been locked since it is deemed as resolved. If you feel the issue is still present or needs attention once again, please raise a new issue.
