### ISSUE TITLE
Specifying port in config

### ISSUE THREAD

**Issue by katiepeters** [mzabriskie/axios#187] opened 2016-01-05 21:56 UTC
Any chance you can add port as part of the config options? Right now, it looks like port is being grabbed from config.url, but the option to specify a different port would be excellent.

**Comment by tony-kerz** [comment] 2016-01-08 02:54
coincidentally, i was just looking for the same thing. typically, i use from the browser, so going back to the origin is fine, in this case, i was looking to use from an express app to go to a diff origin and i can't seem to find the right config to specify port. granted, it could easily be operator error...

**Comment by mzabriskie** [comment] 2016-01-17 21:47
@katiepeters what is your use case for specifying a port? I'm open to supporting this, just want to understand how it would be used.

**Comment by kcjonson** [comment] 2016-03-16 19:22
Example use case would be when the class doing the get/post doesn't actually know what the full baseUrl is, but does know what port the request needs to happen on.

`axios.get('/api/items', {port: 9091}).then(...`

In my case I'd rather not hardcode or rely on a global for where the server actually is, particularly for the switch for dev/prod and just rely on the browsers mechanism to resolve it to the same domain.

**Comment by katiepeters** [comment] 2016-04-04 16:29
Apologies for letting this issue go stale. @mzabriskie if you don't want to support it, all good.

I worked around it by intercepting all incoming axios requests to my Express server and assembling the config url based on environment variables

**Comment by nickuraltsev** [comment] 2016-04-05 01:59
@katiepeters Could you please elaborate on your use case?

**Comment by nickuraltsev** [comment] 2016-04-18 18:44
Closing this due to inactivity. Please feel free to reopen if needed.

**Comment by OliverUv** [comment] 2016-05-17 06:37
I would also like this feature. Usecase is the same as that of @kcjonson 

I have other services running on the same host, on weird ports, but I don't necessarily know which host I'm currently on. Can work around it by grabbing this from configs that differ on dev/host environments, but being able to use the standard '/location' uri scheme along with port specification would be nice.

**Comment by jousby** [comment] 2016-05-26 03:59
+1 similar usecase.

**Comment by usergit** [comment] 2016-05-26 09:07
I second this, it would be useful to specify a port as one of the config options

**Comment by liorsaar1** [comment] 2016-07-01 16:23
+1.
Use case:  the target url has 3 services running on it, at 80, 8000 and 9000. So the url is compose of:

host + port + endpoint + args

It would be great to specify those like in the original 'http'.

**Comment by mzabriskie** [comment] 2016-07-16 19:45
I'm trying to sort out the implementation for this. Feedback appreciated.

Assume global config:

```js
axios.defaults.port = 8080;
```

## Obvious scenarios

### 1. Path with no URL

For a simple path, the port can simply be inserted.

```js
axios.get('/foo/bar');
// :8080/foo/bar
```

### 2. Path and params with no URL

Same can easily be done with params.

```js
axios.get('/foo/bar', { params: { ID: 12345 } });
// :8080/foo/bar?ID=12345
```

## Ambiguous scenarios

### 3. URL with no port

It becomes unclear how to handle for cases where the full URL is provided.

```js
axios.get('http://127.0.0.1/foo/bar');
// http://127.0.0.1:8080/foo/bar ???
```

### 4. URL with port

What happens when a URL is provided that already has a port specified?

```js
axios.get('http://127.0.0.1:3000/foo/bar');
// http://127.0.0.1:8080/foo/bar ???
```

## Implementation

I suggest implementing 1-2 and ignoring 4. I am not certain about 3. Should port config take precedence or should an explicit URL?

**Comment by liorsaar1** [comment] 2016-07-17 02:43
Looking for something that looks like node's http:
```
http.get({
  hostname: 'localhost',
  port: 80,
  path: '/',
}, (res) => {
  // Do stuff with response
})
```
Since all my api calls are:  host, port, path, args.

**Comment by rubennorte** [comment] 2016-07-20 21:04
What about configuring axios dynamically with that information? E.g.:

```javascript
var port = 8080;
axios.defaults.baseURL = location.protocol + '//' + location.hostname + ':' + port;
```

**Comment by nickuraltsev** [comment] 2016-07-25 05:55
I would suggest to implement it so that the `port` option always take precedence if specified (including scenarios 3 and 4).

**Comment by rubennorte** [comment] 2016-08-10 23:46
I don't really see the need to add complexity to the library when there aren't so many use cases for this and the solution in "user-land" is so simple. We don't allow specifying URL parts (only baseURL) so I don't think we should do an exception only for the port.

**Comment by benwiley4000** [comment] 2016-09-15 22:39
@mzabriskie I think 1 and 2 should be implemented, both 3 and 4 ignored. It's absolutely expected behavior that the port should be 80 if not specified in the URL.

I think @rubennorte slightly misses the point with the suggestion to configure using the `location` object, which isn't available in Node.

My use case is wanting to make localhost fetches directly from my Node server, which isn't running on port 80. In production the proxy server would be able to forward requests, but I'm not testing in production! If I specify `http://` in front of `localhost`, then I'm hard-coding the transfer protocol, which is bad.

**Comment by SimonDKnight** [comment] 2016-09-27 08:49
Any news on this? I really need to specify port on my axios requests. Thanks

**Comment by nerdgore** [comment] 2016-11-18 16:10
What about template strings?
```javascript
axis.get(`http://localhost:${config.port}/path/to/resource`)
    .then(onSuccess)
    .catch(onError);
```

But maybe I am missing something...

**Comment by raitucarp** [comment] 2017-02-24 09:39
what is the status of this issue? Please update, application with port will broke your code

**Comment by rubennorte** [comment] 2017-04-02 13:13
I'm closing this as we don't support specifying other granular urls parts as host or protocol and it can be implemented in user-land.

**Closed by rubennorte** 2017-04-02 13:13 UTC
Labels: feature

**Comment by evsign** [comment] 2017-04-16 23:49
Ammm.... Possibility to specify port is part of uri specification. https://tools.ietf.org/html/rfc3986#section-3.2.3
@mzabriskie what problem to add support in this way? if port specified in uri - use specified, if not - use default. Typical strategy from specification.
Very suprised that axios doesn't support port providing. Maybe i just not found this, but right now there are no way to specify port in `baseUrl` for request.

**Comment by amackintosh** [comment] 2017-08-15 02:11
Just found this page after scavenging the docs for a while. Our use case is connecting from a graphQL resolver gateway to an http microservice express server running on non standard port since there's 12 of them.

**Comment by streetrun** [comment] 2018-09-29 19:07
> Any news on this? I really need to specify port on my axios requests. Thanks

heywanted to know, did you get the solution to this. I ahve the same issue now

**Comment by jaclas** [comment] 2019-01-11 14:15
how to set port? it is possible without string concatenation?
