### ISSUE TITLE
Support for streaming connections?

### ISSUE THREAD

**Issue by lynnard** [mzabriskie/axios#505] opened 2016-10-27 11:13 UTC
For example, twitter uses stream api to publish tweet updates in a single http connection via chunked encoding.

I'm doing something similar with one of my servers for a publish-subscribe model.

As far as I can tell, axios doesn't support chunked encoding at the moment - if I just do a `.get` it just keeps going forever without triggering `.then` and there's no way to handle new data as it arrives.

**Comment by nickuraltsev** [comment] 2016-10-29 04:29
Duplicate of #479

**Closed by nickuraltsev** 2016-10-29 04:29 UTC
