### ISSUE TITLE
Setting default Content-Type header is not working.

### ISSUE THREAD

**Issue by damianprzygodzki** [mzabriskie/axios#373] opened 2016-07-10 11:38 UTC
I've set `axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';` and using the same instance doesn't affect at any request at all. It is very annoying because every POST request to API is useless. 

In addition, v: 0.12.0, no interceptor, pure default + post request.

**Comment by mzabriskie** [comment] 2016-07-13 20:18
Duplicate of #362

**Closed by mzabriskie** 2016-07-13 20:18 UTC
