### ISSUE TITLE
Axios vs jQuery post CORS issue

### ISSUE THREAD

**Issue by benjamingeorge** [mzabriskie/axios#113] opened 2015-09-25 20:51 UTC
When doing a CORS post request, jQuery succeeds but Axios gets a CORS error in the console.  

This gets a CORS error
```
Axios.post(endpoint, { email_address : emailAddress})
      .then(function (response) {
        isSentSuccessful = true;
      })
      .catch(function (response) { 
        errorAnimation();
      });
```

But this works
```
    jQuery.post(endpoint, { email_address : emailAddress },
        function(resp){
         isSentSuccessful = true;
        })
        .fail(function(resp){
          errorAnimation();
        });
```

Am I missing something with Axios?  My server is already configured for CORS requests.

**Comment by mzabriskie** [comment] 2015-09-25 21:03
What is the error that you are getting?

**Comment by benjamingeorge** [comment] 2015-09-25 21:07
```
OPTIONS 
XMLHttpRequest cannot load http://example/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://example.dev' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by mzabriskie** [comment] 2015-09-30 15:27
What browser are you using when you get this error?

**Comment by benjamingeorge** [comment] 2015-09-30 16:45
Chrome 45

**Comment by mzabriskie** [comment] 2015-09-30 16:59
Will you try making this request from your app, and let me know the result?

```js
axios.get('https://api.github.com/users/benjamingeorge')
  .then(function (res) {
    console.log(res.data);
  })
  .catch(function(res) {
    if(res instanceof Error) {
      console.log(res.message);
    } else {
      console.log(res.data);
    }
  });
```

**Comment by benjamingeorge** [comment] 2015-10-06 14:31
Sorry for the delay.  I get an object back with all the data.  Again, it's not get methods that are the problem, it's the POST method that has the issue.

**Comment by neverfox** [comment] 2015-10-07 17:42
Same thing, same browser. I've never had a CORS problem calling a public web API from browser code. This is my first time using axios, so maybe I'm just doing it wrong.

**Comment by peterpuzos** [comment] 2015-11-16 13:37
+1

**Comment by arpitHub** [comment] 2015-11-24 10:50
+1

**Comment by anttti** [comment] 2015-12-05 07:37
Stumbled upon this very same issue. jQuery AJAX POST works, Axios (and isomorphic-fetch FWIW) POSTs fail in the preflight phase. What's even more weird is if I "Copy as cURL" both of the requests from Chrome inspector's network tab, they're identical!

**Comment by Homyk** [comment] 2015-12-09 14:46
+1

**Comment by rafaeleyng** [comment] 2015-12-23 17:41
+1

**Comment by rafaeleyng** [comment] 2015-12-23 17:45
I was setting up a little API to learn Grails. Doing a POST request, only by changing from jQuery to Axios, I went from getting this:

![screen shot 2015-12-23 at 3 36 45 pm](https://cloud.githubusercontent.com/assets/4842605/11981697/2ad980e0-a98c-11e5-9c72-927b371ed224.png)

to this:

![screen shot 2015-12-23 at 3 35 43 pm](https://cloud.githubusercontent.com/assets/4842605/11981700/330b8d1c-a98c-11e5-9014-b869db5e78e1.png)

**Comment by ajacquelin** [comment] 2015-12-30 17:01
+1

**Comment by peterpuzos** [comment] 2015-12-30 19:59
Homyk -> What CORS setting did you change on the server side to properly accept application/json in preflight with AXIOS?  Can you explain?  For example, I am using Tomcat, and sending post requests "with credentials" and Axios is not working for us.

**Comment by Homyk** [comment] 2015-12-31 10:03
peterpuzos -> I`m using embedded Jetty, but an equivalent will exist for tomcat.

FilterHolder filter = new FilterHolder();
filter.setInitParameter("allowedOrigins", "*");
filter.setInitParameter("allowedMethods", "POST,GET,OPTIONS,PUT,DELETE,HEAD");
filter.setInitParameter("allowCredentials", "true");
CrossOriginFilter corsFilter = new CrossOriginFilter();
filter.setFilter(corsFilter);

allowedOrigins setting should have a specific IP in prod.

**Comment by peterpuzos** [comment] 2015-12-31 15:51
Thanks for the advice.  We actually managed to get it working after doing some reconfiguration (removed CXF from the equation).  We can confirm that it doesn't seem to be an AXIOS issue at all! Cheers!

**Comment by mdarif** [comment] 2016-03-28 08:54
+1

**Comment by dmavrin** [comment] 2016-03-29 11:17
+1

**Comment by mcfa77y** [comment] 2016-03-30 09:32
+1

**Comment by AndrejGajdos** [comment] 2016-04-02 14:49
+1

**Comment by f14c0** [comment] 2016-04-06 17:30
+1

**Comment by steelx** [comment] 2016-04-27 13:22
+1

**Comment by leyume** [comment] 2016-04-28 19:06
Another way to deal with this, especially if it works in jQuery
<pre>
var config = {
       headers: {
             'Content-Type': 'application/x-www-form-urlencoded'
       },
       params: {
             email_address: emailAddress
       }
};

axios.post( endpoint, {}, config)
.then(function (response) {
       console.log(response);
})
.catch(function (response) {
       console.log(response);
});
</pre>

From Homyk comment on Dec 9, 2015, was able to come up with this and it worked.

**Comment by steelx** [comment] 2016-04-29 05:01
still doesnt work, you can check it here, OPTIONS call goes thru, but POST call fails
https://reduxapp.herokuapp.com/signin

**Comment by pdewouters** [comment] 2016-05-14 11:54
@steelx were you able to find a solution? I have the same issue, OPTIONS is successful. but POST throws an error.

**Comment by dhirajbasukala** [comment] 2016-06-22 10:22
Spent almost a day testing POST request via Axios with unsuccessful result. The Jquery worked just out of the box. After trying out all suggested setting none worked and frustrating. Later I compared the data being sent by Axios POST and jquery POST and the source format in Chrome Dev Tool showed; jquery sent data in the url string fromat i.e., `x=1&y=10&z=abc...` while I was sending data via Axios as 
json object `{x:1, y:10,z:"abc"}` as shown in examples. Later I changed it to url string format and it just worked. Hope it helps some one. However I don't know why it worked at first place, since all the examples in git repo shows sending json object in post requst.

**Comment by unuigbee** [comment] 2016-07-03 22:28
Hi @dhirajbasukala I'm having the same issue. Can you post an example please?

**Comment by crazy4groovy** [comment] 2016-07-04 19:41
+1 issue

**Comment by dhirajbasukala** [comment] 2016-07-05 05:54
@unuigbee, below is example that worked for me.
`axios.post(url,'key1=value1&key2=value2',{withCredentials: true})
.then((res)=>{console.log(res))
.catch((res)=>{console.log(res))` 

where as earlier JSON object being sent case didnt' work which was as below: 
`axios.post(url,{"key1":"value1","key2":"value2"},{withCredentials: true})
.then((res)=>{console.log(res))
.catch((res)=>{console.log(res))` 

I hope it helps.

**Comment by unuigbee** [comment] 2016-07-05 18:15
@dhirajbasukala Thanks I tried it but it didn't work. I had to set Headers for Access-Control-Allow-Origin to all (*) on my dev server. I know it's not safe but I had to for testing purposes.

**Comment by hadv** [comment] 2016-07-12 09:13
+1

**Comment by image72** [comment] 2016-07-18 18:13
maybe you need check server accepts content type, I used angular $http from jquery.ajax encounter this problem.
just set like that
```
$httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';

```

**Comment by AykutCevik** [comment] 2016-07-26 16:07
**+1**

I'm also having problems when headers are set. Every requests is getting the method "OPTIONS" and can not be routet on the server. It is generating an error with "Network Error" as a message. Printing the config shows me, that it should has send the request with the correct method (like GET), but its sending it with OPTIONS.

Does not work, produces "method: options"-requests:
```
this.client = axios.create({
            baseURL: "http://example.org",
            timeout: 30000,
            headers: {'X-FOO-BAR: 'fooobar'}
        });
```
Ningx-log look like:
```
192.168.1.140 - - [26/Jul/2016:17:56:40 +0200] "OPTIONS /ping HTTP/1.1" 400 32 "about:blank" "Node.js (darwin; U; rv:v6.3.1) AppleWebKit/537.36 (KHTML, like Gecko)"
```

Works, produces requests like "method: get" etc.:
```
this.client = axios.create({
            baseURL: "http://example.org",
            timeout: 30000
        });
```
Ningx-log look like:
```
192.168.1.140 - - [26/Jul/2016:17:56:09 +0200] "GET /ping HTTP/1.1" 200 6 "about:blank" "Node.js (darwin; U; rv:v6.3.1) AppleWebKit/537.36 (KHTML, like Gecko)"

```

**Comment by rubennorte** [comment] 2016-08-08 19:39
I'm closing this issue as it's the expected behaviour. We're considering adding a new parameter to automatically configure the `content-type` and the `data` parsing, but that's a different issue.

**Closed by rubennorte** 2016-08-08 19:39 UTC

**Comment by afilp** [comment] 2016-10-11 13:59
@rubennorte Is this automatic configuration implemented?

**Comment by afilp** [comment] 2016-10-15 17:01
@mzabriskie  Is the above automatic configuration idea about to be implemented? It appears that this makes it difficult to use **axios**, for certain use cases. Thanks in advance!

**Comment by cocovon** [comment] 2017-02-09 09:44
I tried param like "a=3&b=4", it works

**Comment by Pau1fitz** [comment] 2017-02-15 16:20
+1

**Comment by bboydflo** [comment] 2017-03-15 10:12
as @leyume said, if it worked with jquery, than passing config object with headers
` headers: {
     'Content-Type': 'application/x-www-form-urlencoded'
  },`

fixed the problem for me. Also make sure to have "Access-Control-Allow-Origin" = "*" set on the server side.

**Comment by jartaud** [comment] 2017-03-25 19:54
I've spent all night trying to make axios work. It always send OPTIONS instead of POST and my CORS cofiguration gets ignored. Vue Resource works for me.

**Comment by allexon** [comment] 2017-04-13 14:41
HTTPS cors HTTP? Hello, how do I communicate using React axios. Accurate
Localhost request: https: appmix: 3001
Server: http://cepaberto.com.br/api/v2/cep.json?cep=xxxxxxxxx

**Comment by Jerjomins** [comment] 2017-09-21 10:42
+1

**Comment by apurav2007** [comment] 2017-11-06 13:02
+1

**Comment by jacekgalazka** [comment] 2018-01-24 12:55
you can must use qs to serialize your data
`const qs = require('qs');
const data = qs.stringify({
    data1: 'a',
    data2: 'a',
   data3: 'a',
  });
axios.get('host', data, {
    'Accept': 'application/json',
    'Content-Type': 'application/x-www-form-urlencoded',
  })`

**Comment by krypton-code** [comment] 2018-02-02 16:13
+1

**Comment by mkyukov** [comment] 2018-06-05 15:08
+1

**Comment by maynardewm** [comment] 2018-08-03 20:16
+1

**Comment by Ethan0007** [comment] 2019-01-22 09:41
Hello,

I just want to ask if how can i do it in get request when in CORS?
it seems its not working when i tried this:
![image](https://user-images.githubusercontent.com/12542052/51526110-38cc8080-1e64-11e9-84fc-a56eb5306abd.png)

But when i used jquery get request, it allows me to access the api.

Thanks.

**Comment by travisC** [comment] 2020-05-19 20:09
@Ethan0007 Swap your header to:

headers: { "Content-Type": "application/x-www-form-urlencoded" },

Otherwise the server/api will need to accept application/json. See the example above for the backend fix in jetty:
https://github.com/axios/axios/issues/113#issuecomment-168160429
