### ISSUE TITLE
this.defaults shared between extended Axios

### ISSUE THREAD

**Issue by reggi** [mzabriskie/axios#391] opened 2016-07-28 17:21 UTC
Here's an example where `Alpha` and `Beta` both extend `Axios` and when you log instances of these classes you can see that `this.defaults.headers` are shared between the two classes. 

The expected behavior would be that `alpha` would only contain the `alpha` header and `beta` would only contain `beta`. 

Any idea why this is not the case and how a PR can be made to fix this?

```js
import { Axios } from 'axios'

export class Alpha extends Axios {
  constructor () {
    super()
    this.alpha = 'alpha'
    this.defaults.headers.alpha = 'alpha'
  }
}

export class Beta extends Axios {
  constructor () {
    super()
    this.beta = 'beta'
    this.defaults.headers.beta = 'beta'
  }
}

let alpha = new Alpha()
let beta = new Beta()

console.log(alpha)
console.log(beta)
```

```
Alpha {
  defaults: 
   { transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     headers: 
      { common: [Object],
        patch: [Object],
        post: [Object],
        put: [Object],
        alpha: 'alpha',
        beta: 'beta' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  interceptors: 
   { request: InterceptorManager { handlers: [] },
     response: InterceptorManager { handlers: [] } },
  alpha: 'alpha' }
Beta {
  defaults: 
   { transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     headers: 
      { common: [Object],
        patch: [Object],
        post: [Object],
        put: [Object],
        alpha: 'alpha',
        beta: 'beta' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  interceptors: 
   { request: InterceptorManager { handlers: [] },
     response: InterceptorManager { handlers: [] } },
  beta: 'beta' }
  ```

**Comment by reggi** [comment] 2016-07-28 17:28
sending the defaults through super works

```js
import { Axios } from 'axios'

export class Alpha extends Axios {
  constructor () {
    super({headers: {'alpha': 'alpha'}})
  }
}

export class Beta extends Axios {
  constructor () {
    super({headers: {'beta': 'beta'}})
  }
}

let alpha = new Alpha()
let beta = new Beta()

console.log(alpha)
console.log(beta)
```

and cloning `this.default` works

```js
import { Axios } from 'axios'
import { cloneDeep } from 'lodash'

export class Alpha extends Axios {
  constructor () {
    super()
    this.defaults = cloneDeep(this.defaults)
    this.alpha = 'alpha'
    this.defaults.alpha = 'alpha'
  }
}

export class Beta extends Axios {
  constructor () {
    super()
    this.defaults = cloneDeep(this.defaults)
    this.beta = 'beta'
    this.defaults.beta = 'beta'
  }
}

let alpha = new Alpha()
let beta = new Beta()

console.log(alpha)
console.log(beta)
```

**Comment by reggi** [comment] 2016-07-28 17:30
Just to note changes to defaults root level do not transfer to the other class, only changes to defaults one level deeper, like to `headers`.

**Comment by reggi** [comment] 2016-07-28 17:32
Just figured it out, it's because this merge isn't a deep merge. 

https://github.com/mzabriskie/axios/blob/master/lib/utils.js#L227-L258

**Comment by inv8der** [comment] 2016-08-02 22:31
I'm experiencing this issue, too. My guess is that with how the defaults are merged for each instance, the `defaults` attribute is just a shallow copy of the global `axios.defaults`

```
import axios from 'axios';
const client = axios.create();

console.log(axios.defaults.headers.common.Authorization);  // undefined
console.log(client.defaults.headers.common.Authorization); // undefined  

client.defaults.headers.common.Authorization = 'Token foobar'

console.log(axios.defaults.headers.common.Authorization);  // 'Token foobar'
console.log(client.defaults.headers.common.Authorization); // 'Token foobar'
```

**Comment by inv8der** [comment] 2016-08-03 16:17
Duplicate of #385? I know my issue is ☝️

**Comment by reggi** [comment] 2016-08-03 18:18
Yeah this was my solution:

```
import { Axios as AxiosRoot } from 'axios'
import { cloneDeep } from 'lodash'

export default class Axios extends AxiosRoot {
  constructor () {
    super()
    this.defaults = cloneDeep(this.defaults)
    this.interceptors = cloneDeep(this.interceptors)
    return this
  }
}
```

**Comment by nickuraltsev** [comment] 2016-08-03 18:58
Thank you! Yes, looks like we need to deep clone configs. Closing as #385 already covers this.

**Closed by nickuraltsev** 2016-08-03 18:58 UTC

**Comment by matiishyn** [comment] 2017-04-12 12:41
thanks @reggi for your solution but this doesn't work for me.
And the issue is still present in the newest version.

I've also tried this way:

```js
// BASE URL
axios.defaults.baseURL = CONFIG.API_SERVER;

// SEPARATE INSTANCES
const authAxios = axios.create();
authAxios.defaults = _.cloneDeep(authAxios.defaults);

const apiAxios = axios.create();
apiAxios.defaults = _.cloneDeep(apiAxios.defaults);

// SETTING JWT HEADER
const savedToken = LS.getJwt();
if (savedToken) {
  apiAxios.defaults.headers.common.Authorization = `JWT ${savedToken}`;    
  // ^=== this will set headers to both instances :( 
}

console.log(authAxios.defaults);
console.log(apiAxios.defaults);
```

But both `authAxios` and `apiAxios` instances have the `Authorization` headers.

Did anyone fix it somehow?

**Comment by jamessawyer** [comment] 2018-07-02 08:08
same issue! I have stuck for this for days
