### ISSUE TITLE
Unit testing interceptors 

### ISSUE THREAD

**Issue by laumair** [mzabriskie/axios#511] opened 2016-10-30 19:08 UTC
So, I have added this response interceptor that would basically just clear out the localstorage items if the status is 401. I haven't have found luck with unit testing it: 

```
axios.interceptors.response.use((response) => {
  if (response.status === 401) {
    storage.clear();
  }
  return response;
});
```

I have tried moxios but haven't been lucky with it when it comes to interceptors.

**Comment by yanivefraim** [comment] 2016-11-08 18:33
What about somw kind of integration test for that? You can use nock to simulate 401 response, and then to make your axios call, and check that storage is cleared.

**Comment by nickuraltsev** [comment] 2016-11-25 07:02
Closing as this is more of a StackOverflow question than an axios issue.

**Closed by nickuraltsev** 2016-11-25 07:02 UTC

**Comment by lmammino** [comment] 2017-07-24 12:08
What I tend to do in those cases is to invoke the interceptors directly and provide a fake response or a fake error:

```
client.interceptors.response.handlers[0].fulfilled({data: 'foo'})
```

**Comment by lmammino** [comment] 2017-07-24 12:15
To be more specific, if I have the following interceptor:

```javascript
  const instance = axios.create()
  instance.interceptors.response.use(
    response => response.data,
    err => {
      const error = new Error(err.response.statusText)
      error.statusCode = err.response.status
      error.data = err.response.data
      return Promise.reject(error)
    }
  )
```

This is how I test it with jest:

```javascript
expect(client.interceptors.response.handlers[0].fulfilled({data: 'foo'})).toBe('foo')
  expect(client.interceptors.response.handlers[0].rejected({
    response: {
      statusText: 'NotFound',
      status: 404,
      data: {message: 'Page not found'}
    }
  })).rejects.toMatchObject({
    message: 'NotFound',
    statusCode: 404,
    data: {message: 'Page not found'}
  })
```

I hope this is still useful, even if the original issue is dated almost a year ago :)

**Comment by suminksudhi** [comment] 2018-12-24 09:06
@lmammino 
Hi,
what is the "client" in the above snippet 
Is it the instance of axios.create or something I may have missed?

**Comment by psychosis448** [comment] 2019-01-30 10:12
@suminksudhi that is your axios instance

**Comment by okovalov** [comment] 2019-02-02 02:59
> To be more specific, if I have the following interceptor:
> 
> ```js
> const instance = axios.create()
> instance.interceptors.response.use(
>   response => response.data,
>   err => {
>     const error = new Error(err.response.statusText)
>     error.statusCode = err.response.status
>     error.data = err.response.data
>     return Promise.reject(error)
>   }
> )
> ```
> 
> This is how I test it with jest:
> 
> ```js
> expect(client.interceptors.response.handlers[0].fulfilled({data: 'foo'})).toBe('foo')
> 
> expect(client.interceptors.response.handlers[0].rejected({
>   response: {
>     statusText: 'NotFound',
>     status: 404,
>     data: {message: 'Page not found'}
>   }
> })).rejects.toMatchObject({
>   message: 'NotFound',
>   statusCode: 404,
>   data: {message: 'Page not found'}
> })
> ```
> 
> I hope this is still useful, even if the original issue is dated almost a year ago :)

It looks like I am getting there. My only problem is that handlers are empty.. Maybe because I use mocking?.. but I had to use it otherwise I could not deal with that annoying 'axios.create() undefined error!' 

not sure what I am doing wrong..

here is my __mocks__/axios.js

```js
const mockAxios = jest.genMockFromModule('axios')

// this is the key to fix the axios.create() undefined error!
mockAxios.create = jest.fn(  () => mockAxios)

export default mockAxios
```

here is the Api (axios instance I use)

```js
import axios from 'axios'
import { API_ROOT } from '../configs/api'

const Api = axios.create({
  baseURL: API_ROOT,
  headers: { 'Content-Type': 'application/json' }
})

Api.interceptors.request.use(
  function(config) {
    /** For the future authentication routine **/
    const token = localStorage.getItem('user')

    if (token) config.headers.Authorization = `Bearer ${token}`
    console.log('req fullfilled config', config)

    return config
  },
  function(error) {
    console.log('req rejected error', error)

    return Promise.reject(error)
  }
)

Api.interceptors.response.use(
  (response) => {
    console.log('response ok ')
  
    return response
  },
  (error) => {
    console.log('response rejected error', error)

    return Promise.reject(error.response)
})

export default Api

```

and here is the test

```js
import Api from  '../../services/api'
import * as Methods from "../../constants/methods"
import mockAxios from 'axios'


test('calls `axios()` with `endpoint`, `method` and `body`', async () => {
  mockAxios.get.mockImplementationOnce(async () =>
    Promise.resolve( dataToReturn ),
  )
  
  const dada = await Api.get(Methods.GET,'comments', {})
  
  expect(dada).toEqual( dataToReturn) // it works fine obviously
  
  console.log('Api.interceptors.request', Api.interceptors.request) // here I see that handlers are empty

  expect(mockAxios.interceptors.request.handlers[0].fulfilled({data: 'foo'})).toBe('foo') // this one obviously fails because handlers are empty...
  
  
})
```

please advise what I am missing?

thank you

**Comment by rs-8** [comment] 2019-02-26 18:49
> > To be more specific, if I have the following interceptor:
> > ```js
> > const instance = axios.create()
> > instance.interceptors.response.use(
> >   response => response.data,
> >   err => {
> >     const error = new Error(err.response.statusText)
> >     error.statusCode = err.response.status
> >     error.data = err.response.data
> >     return Promise.reject(error)
> >   }
> > )
> > ```
> > 
> > 
> > This is how I test it with jest:
> > ```js
> > expect(client.interceptors.response.handlers[0].fulfilled({data: 'foo'})).toBe('foo')
> > 
> > expect(client.interceptors.response.handlers[0].rejected({
> >   response: {
> >     statusText: 'NotFound',
> >     status: 404,
> >     data: {message: 'Page not found'}
> >   }
> > })).rejects.toMatchObject({
> >   message: 'NotFound',
> >   statusCode: 404,
> >   data: {message: 'Page not found'}
> > })
> > ```
> > 
> > 
> > I hope this is still useful, even if the original issue is dated almost a year ago :)
> 
> It looks like I am getting there. My only problem is that handlers are empty.. Maybe because I use mocking?.. but I had to use it otherwise I could not deal with that annoying 'axios.create() undefined error!'
> 
> not sure what I am doing wrong..
> 
> here is my **mocks**/axios.js
> 
> ```js
> const mockAxios = jest.genMockFromModule('axios')
> 
> // this is the key to fix the axios.create() undefined error!
> mockAxios.create = jest.fn(  () => mockAxios)
> 
> export default mockAxios
> ```
> 
> here is the Api (axios instance I use)
> 
> ```js
> import axios from 'axios'
> import { API_ROOT } from '../configs/api'
> 
> const Api = axios.create({
>   baseURL: API_ROOT,
>   headers: { 'Content-Type': 'application/json' }
> })
> 
> Api.interceptors.request.use(
>   function(config) {
>     /** For the future authentication routine **/
>     const token = localStorage.getItem('user')
> 
>     if (token) config.headers.Authorization = `Bearer ${token}`
>     console.log('req fullfilled config', config)
> 
>     return config
>   },
>   function(error) {
>     console.log('req rejected error', error)
> 
>     return Promise.reject(error)
>   }
> )
> 
> Api.interceptors.response.use(
>   (response) => {
>     console.log('response ok ')
>   
>     return response
>   },
>   (error) => {
>     console.log('response rejected error', error)
> 
>     return Promise.reject(error.response)
> })
> 
> export default Api
> ```
> 
> and here is the test
> 
> ```js
> import Api from  '../../services/api'
> import * as Methods from "../../constants/methods"
> import mockAxios from 'axios'
> 
> 
> test('calls `axios()` with `endpoint`, `method` and `body`', async () => {
>   mockAxios.get.mockImplementationOnce(async () =>
>     Promise.resolve( dataToReturn ),
>   )
>   
>   const dada = await Api.get(Methods.GET,'comments', {})
>   
>   expect(dada).toEqual( dataToReturn) // it works fine obviously
>   
>   console.log('Api.interceptors.request', Api.interceptors.request) // here I see that handlers are empty
> 
>   expect(mockAxios.interceptors.request.handlers[0].fulfilled({data: 'foo'})).toBe('foo') // this one obviously fails because handlers are empty...
>   
>   
> })
> ```
> 
> please advise what I am missing?
> 
> thank you

Did you find a solution?

**Comment by okovalov** [comment] 2019-03-01 01:31
@rs-8 unfortunately, no

**Comment by m-sureshraj** [comment] 2019-03-07 07:53
Hi @okovalov, I think the issue is because of **mocking** `axios` module. 

with mocking
```js
jest.mock('axios');
console.log(axios.interceptors.response.handlers);
```
output:

![image](https://user-images.githubusercontent.com/12813750/53939574-7a924d00-40d9-11e9-9c81-c5015f2392be.png)

without mocking
```js 
console.log(axios.interceptors.response.handlers);
```

output:

![image](https://user-images.githubusercontent.com/12813750/53939690-d8bf3000-40d9-11e9-8aae-4d87b63d3511.png)

**here is the working example**
```js
// interceptors.js
import axios from 'axios';

export function initUnauthorizedResponseInterceptor() {
    axios.interceptors.response.use(
        res => res,
        error => {
            if (error.response.status === 403) {
                window.location.replace('/login');
                return;
            }

            return Promise.reject(error);
        },
    );
}
```

```js
// interceptors.spec.js
import axios from 'axios';
import * as interceptor from '../interceptors';

describe('Interceptors', () => {
    describe('initUnauthorizedResponseInterceptor', () => {
        interceptor.initUnauthorizedResponseInterceptor();

        it('should throw error if response status is other then 403', () => {
            const res = {
                response: { status: 401 },
            };
            const rejectedRes = axios.interceptors.response.handlers[0].rejected(res);

            expect(rejectedRes).rejects.toMatchObject(res);
        });

        it('it should redirect to login page if response status is 403', () => {
            // global is `window` in jest
            global.location.replace = jest.fn();

            const rejectedRes = axios.interceptors.response.handlers[0].rejected({
                response: { status: 403 },
            });

            expect(global.location.replace).toBeCalledWith('/login');
            expect(rejectedRes).toBeUndefined();
        });
    });
});
```

cc - @rs-8

**Comment by crhistianramirez** [comment] 2019-08-09 01:52
@m-sureshraj  so just to clarify, the solution was to *not* mock axios? So... is there a way *to* mock axios?

**Comment by rs-8** [comment] 2019-08-09 10:26
> @m-sureshraj so just to clarify, the solution was to _not_ mock axios? So... is there a way _to_ mock axios?

For mocking any http requests in node you can use [nock](https://github.com/nock/nock)
I used it and didn't have any prooblem with it.

**Comment by emileber** [comment] 2019-08-14 17:28
I wrote the [`axios-middleware`](https://emileber.github.io/axios-middleware/#/examples/testing) module to ease testing and write self-contained middlewares.

**Comment by caiobiodere** [comment] 2020-01-20 02:08
instead of using jest axios mock solution I've found this way much easier and it also works with interceptors

https://gist.github.com/cowboy/44ae5deed5d04d2cf28f2087fde2c89c
