### ISSUE TITLE
axios is not sending auth information

### ISSUE THREAD

**Issue by nikea1** [mzabriskie/axios#642] opened 2017-01-09 19:27 UTC
I've been trying to send a GET call to the stormpath API which requires some authorization to access the tenant data. When using Postman to test it worked just fine. Same result with curl. But when I tried using axios in my react app I get a 401 error. 

`XMLHttpRequest cannot load https://api.stormpath.com/v1/tenants/current. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 401.`

this is what I used
```
 axios({	
  method: 'get',
  url: "https://api.stormpath.com/v1/tenants/current", 
  auth:
        {
          username: 'api ID',
          password: 'api Secret'
        }
}).then(function(response){console.log(response)})
```

I don't know why but it's not delivering the username and password according to the response I got.

```
code:401
developerMessage:"Authentication with a valid API Key is required."
message:"Authentication required."
moreInfo:"http://www.stormpath.com/docs/quickstart/connect"
requestId:"3686f590-d69e-11e6-9b8a-22000a8ce5d1"
status:401
```

But since the keys I used worked for the above previous cases the keys cannot be the problem. It most likely has to do with my configuration right?

**Comment by tsongas** [comment] 2017-02-15 03:22
I recently had a similar issue and it turned out that the browser's OPTIONS request, which is made in advance of a GET or POST, didn't include the auth info and so the actual GET or POST was never made due to the OPTIONS request error. However, the first error you show is a CORS error. Hmm....

**Comment by nouveller** [comment] 2017-03-10 08:45
I have a similar issue, when using the method helpers (`axios.get`, `axios.post` etc...) the auth is not getting included. But when constructing the request myself using just `axios`, it works as expected.

Working, headers get set:

```js
axios({
  // ...
  auth: {
    user: 'user',
    password: 'password',
  },
});
```

Not working, headers don't get set:

```js
axios.get(url, {
  // ...
  auth: {
    user: 'user',
    password: 'password',
  },
});
```

Perhaps this is expected behaviour? But it is kind of odd you can't use the helper methods _and_ pass through some authentication.

**Comment by nikea1** [comment] 2017-03-15 08:37
Ah, I think I saw something about OPTIONS. That was what threw the 401 error I think. So then how do you make the OPTIONS request take the key and secret? I tried setting them as a header but it still wouldn't take it.

**Comment by kohkimakimoto** [comment] 2017-03-15 10:45
I have same issue.

**Comment by kohkimakimoto** [comment] 2017-03-15 11:58
My issue was about OPTIONS request. Now I don't have any workaround to send auth info with OPTIONS request. But I solved the problem by modifying the server (nginx) configuration to disable basic auth only when clients send OPTIONS requests.

My configuration like the following:

```
location / {
    if ($request_method = OPTIONS ) {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
        add_header Access-Control-Allow-Headers "Origin, Authorization, Accept, Content-Type";
        add_header Access-Control-Allow-Credentials true;
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 200;
    }
    auth_basic "Restricted";
    auth_basic_user_file /path/to/passwordfile;
}
```

**Comment by johnharris85** [comment] 2017-03-20 14:49
Same issue here. OPTIONS gets made a preflight request and the server (which I have no control over) requires auth information and I get a 401. Anyway to make OPTIONS send auth details?

**Comment by rubennorte** [comment] 2017-04-02 14:52
I'm closing as it seems an issue on how the browser handles preflight requests and authorization, not an axios issue.

**Closed by rubennorte** 2017-04-02 14:52 UTC

**Comment by john-harding** [comment] 2017-06-23 15:53
The [W3 specification](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials) says that preflight requests should never include credentials.

**Comment by johan-lejdung** [comment] 2017-08-20 08:18
I just solved this as well by not using `axios.post()`, instead using `axios()`. In my case the OPTIONS request was accepted by the server, but the following POST didn't have any headers in it.

**Comment by reksc** [comment] 2018-03-09 14:09
Experiencing the above issue with the latest axios version - using the shorthand methods to specific request types results in ignoring the auth parameters and ends with a failed Basic Auth strategy.

I'm using Express + Passport on the server side and Axios within the client.

**Comment by CapitanRedBeard** [comment] 2018-04-23 20:42
I get the same issue but has nothing to do with Auth and I get a 403. However if I send the same GET HTTP request just through the chrome browser, it works fine. 

Using these headers:
```
axios({
        method: 'get',
        url: url,
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE',
            'Access-Control-Allow-Headers': 'Origin, Content-Type, X-Auth-Token',
            'Content-Type': 'application/json',
            Pragma: 'no-cache',
            'Access-Control-Expose-Headers': 'Access-Token, Uid'
        }
    })
```

**Comment by SLCH** [comment] 2018-07-06 10:09
Had same issue - was just fine everywhere but in IE.
Switching to fetch did not help.
Switching to axios() did not help.
Adding site to site lists of 'Local intranet', 'Trusted sites' did not help.
Removing Kerberos/negotiate did not help. ( https://stackoverflow.com/questions/16222946/remove-negotiate-from-windowsauthentication-in-iis )

Issue was, site was not in Intranet zone.
Temorary switching from
'Automatic logon only in Intranet zone'
to
'Automatic logon with current user name and password'
in
'Internet options'-'Security'-**'Internet' zone**-'Custom level'-'User Authentication'-'Logon'
solved it for me.

Sooo... it was my bad :man_facepalming:

**Comment by JerryLeeCS** [comment] 2018-08-01 01:29
+1

**Comment by maxzhou0** [comment] 2018-09-24 16:32
same method, post worked,and get didn't

**Comment by sepehr** [comment] 2018-11-09 12:35
It has nothing to do with the http client, no matter Axios or others. Server should be configured in a way that it allows non-authenticated OPTIONS requests. [Read more](https://stackoverflow.com/a/15734032/65732).

**Comment by GabrielDelepine** [comment] 2018-11-19 10:37
@sepehr I agree but Axios still provide the withCredentials option.
Some API is not perfect but we still have to deal with, unfortunately.

**Comment by sepehr** [comment] 2018-11-19 10:49
Sure, we can made a credentialed request to a protected endpoint. However, the thing is that we can’t control browser’s preflight request with Axios or any other http client. @GabrielDelepine

**Comment by GabrielDelepine** [comment] 2018-11-19 11:06
@sepehr preflight request is made by the browser, I understand this point.

But on the current documentation of axios, the option `withCredentials` pretends to be able to control the behaviour of preflight request.

<img width="666" alt="capture d ecran 2018-11-19 a 12 01 50" src="https://user-images.githubusercontent.com/1979087/48703190-43179780-ebf3-11e8-8ffc-3ef8530a19a2.png">

Currently, on Chrome 70, this `withCredentials` does not work for me.
At this point, I don't know if it's an Axios issue or a new policy from the newest version of Chrome and Firefox.

**Comment by PRABIRSOFT** [comment] 2018-12-06 21:53
**In server side try to add this block with your response head**
```
res.header('Access-Control-Allow-Origin', 'http://' + url.parse(req.headers.referer).host)
res.header('Access-Control-Allow-Credentials', true)
res.header('Access-Control-Allow-Methods', 'GET, POST')
res.header('Access-Control-Allow-Headers', 'X-Requested-With,content-type,authorization')
```

**Comment by sloughin** [comment] 2020-02-25 21:47
https://github.com/rubennorte -- I think you closed this too quickly.  Postman and jQuery can both send requests that provide the authentication headers, but it seems axios can't manage to do that!  

This code (in a Vue.js Vuex store action) fails with a 401 (Unauthorized):
`async fetch_stats(context) {
            var headers = {'headers': {
                'Content-Type': 'application/json', 
                'Authorization': 'Token '+context.getters.token}
            };
            console.log(headers);
            var res = await axios.get(
                "http://localhost:8000/api/fetch-stats/",
                {}, headers
            ).then(res => ( console.log(res) )
            ).catch(error => console.log(error));
            return res;
        },`

The console.log(headers) produces the following output in the dev console on the browser:
Content-Type:application/json
Authorization:Token d89afca11b46da8747dd0acabc3d1542a63b26e1

meanwhile this Postman request succeeds:

http://localhost:8000/api/fetch-stats/
with Headers(2) (as shown in BulkEdit mode):
Content-Type:application/json
Authorization:Token d89afca11b46da8747dd0acabc3d1542a63b26e1

I have also found that the jQuery ajax call can be made to pass the headers properly, so I would assert that this is a problem with axios...
