### ISSUE TITLE
Is there a way to force not to use proxy?

### ISSUE THREAD

**Issue by otakustay** [mzabriskie/axios#635] opened 2017-01-06 06:34 UTC
In my case I have a `http_proxy` env variable on my development computer which passes all traffic to my vpn, however this proxy would fail to work when hostname is `localhost`, therefore when I'm testing my application it always fails because I setup my server at localhost, I want a method to force axios receiving a `none` for proxy config, currently if `proxy` property is `null` or `undefined` it will use the `http_proxy` env

**Comment by vilinski** [comment] 2017-02-06 16:36
there is already an open [PR](https://github.com/mzabriskie/axios/pull/565), which if merged solves your problem

**Comment by rubennorte** [comment] 2017-04-02 14:48
Closing as duplicate of #434

**Closed by rubennorte** 2017-04-02 14:48 UTC
