### ISSUE TITLE
SyntaxError: Unexpected token (55:4) lib/axios.js 

### ISSUE THREAD

**Issue by audan2009** [mzabriskie/axios#464] opened 2016-10-02 05:19 UTC
Hi,

I'm using superlogin-client which has a dependency on Axios. I'm just upgrading to the latest version of ionic 2 rc0. I'm getting this error:

SyntaxError: Unexpected token (55:4) in /Users/Dan/Documents/WebProjects/vacayerV3/node_modules/axios/lib/axios.js

Here is more discussion on the issue:

https://github.com/micky2be/superlogin-client/issues/21#issuecomment-250953515

Thanks!

**Comment by nickuraltsev** [comment] 2016-10-06 20:06
Could you please provide a github repo that reproduces the problem?

**Comment by audan2009** [comment] 2016-10-07 12:13
Yes, I will. It will be later tonight until I can put it together.

**Comment by audan2009** [comment] 2016-10-08 02:18
Please see this repo:

https://github.com/audan2009/ionic-superlogin-axios/tree/master/src

Should be able to install ionic, dependencies and run ionic serve

Error:

[21:08:36]  bundle dev failed:  Unexpected token (55:4) in /Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/axios/lib/axios.js

[21:08:36]  SyntaxError: Unexpected token (55:4) in /Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/axios/lib/axios.js
    at Parser.pp$4.raise (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:4070:13)
    at Parser.pp.unexpected (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2268:8)
    at Parser.pp$2.parseBindingAtom (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:3173:10)
    at Parser.pp$1.parseVarId (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2743:18)
    at Parser.pp$1.parseVar (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2726:12)
    at Parser.pp$1.parseVarStatement (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2611:8)
    at Parser.pp$1.parseStatement (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2396:17)
    at Parser.pp$1.parseTopLevel (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2313:23)
    at Parser.parse (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:2180:15)
    at parse (/Users/Dan/Documents/WebProjects/ionc-superlogin/node_modules/rollup/dist/rollup.js:4970:37)

**Comment by sqren** [comment] 2016-10-13 21:09
I'm seeing the same issue when bundling axios with rollup. There's an issue for it here:
https://github.com/rollup/rollup-plugin-commonjs/issues/110

Might be due to protected keyword `default` or similar.

**Comment by sqren** [comment] 2016-10-13 21:12
Removing this seems to fix the problem:
```
module.exports.default = axios;
```

**Comment by audan2009** [comment] 2016-10-13 21:40
I'll give it a shot but that sounds like it's removing axios which means the supeelogin client library won't work.

**Comment by sqren** [comment] 2016-10-13 21:51
I'll only remove the "default" attribute. It's still exported.

**Comment by audan2009** [comment] 2016-10-13 21:56
Oh! Gotcha. Report back soon. Thanks!

**Comment by JamyDev** [comment] 2016-10-13 21:59
There's [a pr](https://github.com/rollup/rollup-plugin-commonjs/pull/117) in the `rollup-plugin-commonjs` module which supposedly resolves this. But whatever works :)

**Comment by audan2009** [comment] 2016-10-14 00:27
@sqren I removed the "default" attribute and now I got this error: 

bundle dev failed:  Unexpected token (70:0) in /Users/Dan/Documents/WebProjects/vacayerV5/node_modules/axios/lib/helpers/isURLSameOrigin.js

I did it in the axios.js file 

I changed it from this at line 41-46:

```
axios.spread = require('./helpers/spread');

module.exports = axios;

// Allow use of default import syntax in TypeScript
module.exports.default = axios;

```
to 


```

axios.spread = require('./helpers/spread');

module.exports = axios;

// Allow use of default import syntax in TypeScript
module.exports = axios;


```

I know it says module.exports twice so I actually just removed one of the lines and still got the same error.

May be that pr update will fix it....

**Comment by sqren** [comment] 2016-10-14 07:54
It's probably better to wait for the PR to be merged. Seems like an issue with rollup rather than Axios.

**Comment by JamyDev** [comment] 2016-10-14 11:19
The PR I mentioned doesn't resolve the issue completely. Looking into what else is going on now.

**Comment by nickuraltsev** [comment] 2016-10-20 04:47
Closing as it's not an axios issue.

**Closed by nickuraltsev** 2016-10-20 04:47 UTC

**Comment by magicspon** [comment] 2017-02-02 11:38
FYI, I'm aware that this is a rollup issue, however as I've just come across the issue I thought i'd share my solution, which is probably not the best but it works.

In package.json i change main to `"main": "dist/axios.js",`

not ideal, but i've not managed to get anywhere with rollup.

ta

**Comment by lukasjuhas** [comment] 2017-02-17 12:18
Thanks @magicspon,

I had similar issue, this seems to be working for me:

`import axios from 'axios/dist/axios';`
