### ISSUE TITLE
node is unhappy with non Error wrapped promise rejections 

### ISSUE THREAD

**Issue by cdaringe** [mzabriskie/axios#306] opened 2016-04-21 23:53 UTC
# problem statement
- node barks with warnings on every rejected 400/500 axios call

specficically, it complains with:

```
Warning: a promise was rejected with a non-error: [object Object]
    at IncomingMessage.handleStreamEnd (/path/to/my/pkg//node_modules/axios/lib/adapters/http.js:112:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

# supplmental context

see reference in where this happens:
```js
// axios/lib/adapters/http.js
      (res.statusCode >= 200 && res.statusCode < 300 ?
        resolve :
        reject)(response);
```

# solution

it's been discussed somewhat in #18, but I think we need to perhaps create a new Error proto, extend from error, and add all the response bits into it.  perhaps provide `.toJSON` to serialize it down nicely to?

**Comment by cdaringe** [comment] 2016-04-21 23:54
FYI, node `4.4.2`

**Comment by mzabriskie** [comment] 2016-04-22 16:00
This is definitely something that needs to be addressed. It has been discussed in a few different issue threads. Would like to have a standardized Error subclass that is issued for all rejected Promises that includes error message along with additional request details.

**Comment by nickuraltsev** [comment] 2016-04-22 19:24
I totally agree that promises should be rejected with an `Error`, but it's going to be a breaking change: 

```js
axios('/foo')
  .catch(error => {
    if (error instanceof Error) {
      // Okay, it's a network failure
    } else {
      // Some code that handles non-2xx responses...
      //
      // The problem is that if we update axios to always reject with an Error 
      // (which is the right thing to do), this code will not be called anymore 
    }
  })
```

**Comment by nickuraltsev** [comment] 2016-04-26 02:19
Closing as duplicate of #24

**Closed by nickuraltsev** 2016-04-26 02:19 UTC
Labels: duplicate
