### ISSUE TITLE
Proxy settings do not work with react-native

### ISSUE THREAD

**Issue by maluramichael** [mzabriskie/axios#672] opened 2017-01-30 10:47 UTC
I pass my proxy object to the axios.request() method and test everything with charles proxy but nothing happens. After some debugging i realized that the http adapter file is not packaged because it is not used.

And the adapter is not used because of this code inside the defaults.js

```js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```
Can someone help me so i can use the proxy feature with react-native?

**Comment by rubennorte** [comment] 2017-02-12 15:26
Closing as duplicate of #648

**Closed by rubennorte** 2017-02-12 15:26 UTC

**Comment by flexy1994** [comment] 2017-03-08 09:50
I still have the same problem with react native 0.42.0.

I created a new react natvie project. Imported axios:

`import axios from 'axios';`

And added a componentDidMount to test the Proxyconnection:

```
return axios.request({
    url: "/health-check",
    baseURL: 'http://my-server.de/api/',
    method: "GET",
    proxy: {
        host: "proxy-ip",
        port: 8888
    }
}).then(response => {
    alert("success");
}).catch((error) => {
    alert("error");
});
```

this is my package.json: 

```
{
  "name": "MyTestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "react": "15.4.2",
    "react-native": "0.42.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I get a success response. But the request is not send through the proxy (Using CharlesProxy to debug).

**Comment by rishabhbhatia** [comment] 2020-04-03 11:42
@maluramichael @flexy1994 Hey how did you manage to solve it?
I'm trying to call a proxy server from react-native and unable to do so, any help would be really appreciated.
