### ISSUE TITLE
How can I catch status = cancelled with axios?

### ISSUE THREAD

**Issue by srahulprdxn** [mzabriskie/axios#293] opened 2016-04-13 07:57 UTC
I disconnected my database and sent a request to the api. The status changed from pending to cancelled in the chrome network tab but nothing got caught as an error.

Is there any mechanism, I am missing, to catch the status = cancelled?

**Comment by nickuraltsev** [comment] 2016-04-15 17:08
Could you please provide code that makes a request and handles errors?

**Comment by srahulprdxn** [comment] 2016-04-17 18:41
@nickuraltsev

http://stackoverflow.com/questions/36591762/how-to-catch-status-cancelled-in-axios

^^ I posted here in detail.. If not a problem, can you please go through the post?

**Comment by devmarco** [comment] 2016-04-25 22:45
I have the same question, and I didn't find anything talking about it.

**Comment by nickuraltsev** [comment] 2016-04-26 01:20
Could you please run the following code in the browser and provide the output?

```js
axios.post(...).then(response => {
  console.log('Success', response);
}).catch(error => {
  console.log('Error', error);
});
```

**Comment by devmarco** [comment] 2016-04-26 01:30
I am not testing exactly @srahulprdxn posted. But I have the same question.

To reproduce you can try following:

Set the timeout for example to 300

```
axios.defaults.timeout = 300;
```

The request will be 'canceled'

<img width="672" alt="screen shot 2016-04-25 at 10 27 47 pm" src="https://cloud.githubusercontent.com/assets/2750520/14803956/025793ea-0b35-11e6-85e1-a01c3524fdeb.png">

We should be able to catch the error on 'catch'.

```
axios.get(...).catch(error => {
  console.log('Get canceled error', error);
});
```

**Comment by nickuraltsev** [comment] 2016-04-26 02:06
Please see the issue #226. It was fixed in 0.10.0. Are you using the latest version of axios?

**Comment by devmarco** [comment] 2016-04-26 02:08
Cool, Thanks for the reply @nickuraltsev

**Comment by srahulprdxn** [comment] 2016-04-26 06:25
@nickuraltsev I'll be posting the result for
```
axios.post(...).then(response => {
  console.log('Success', response);
}).catch(error => {
  console.log('Error', error);
});
```

soon.

**Comment by nickuraltsev** [comment] 2016-05-16 19:08
Closing this due to inactivity. Please feel free to reopen if needed.

**Closed by nickuraltsev** 2016-05-16 19:08 UTC

**Comment by L3V147H4N** [comment] 2016-07-14 06:17
@nickuraltsev im using version 0.13.0 in react native 0.24.1 and it doesn't work, catch doest not fire on timeout, it just goes forever

**Comment by uglymunky** [comment] 2016-09-27 18:51
Hi, I'm seeing this same problem.  I can not get axios to catch on timeout.

My code:

```
axios.get(<some api endpoint>, {timeout: 10}).then(() => { debugger; }).catch(() => { debugger; }).finally(() => { debugger; })
```

In this example, the network tab shows the request as cancelled but none of the handlers get triggered.

**Comment by uglymunky** [comment] 2016-09-27 19:16
...aaand, updating from version 0.9 to the latest version of axios fixed it for me :)

**Comment by ralphsmith80** [comment] 2017-04-17 22:38
I'm seeing this in `0.16.0` did it regress?

**Comment by ralphsmith80** [comment] 2017-04-18 15:34
> I'm seeing this in 0.16.0 did it regress?

Just test this as working as expected with a small python server that returns a 204 so ignore my previous comment.

**Comment by mherodev** [comment] 2018-02-09 21:56
I found my way here because I was running into a silent timeout occurring, so for my past self, here's a tip:

The default timeout for Axios' requests may be longer than the timeout for the parent process, which will swallow this error. Manually set your Axios request timeout to be short and you'll see the error, e.g.

```javascript
axios.get(url, { timeout: 5000 })
```

**Comment by a-eid** [comment] 2018-03-13 11:31
I'm seeing this in `17.1`, 
could somebody explain what is the status of `cancelled`  ?

**Comment by nelsonomuto** [comment] 2019-02-11 03:58
A wrapper I wrote for this ```import axios from 'axios';
const CancelToken = axios.CancelToken;

/**
 * Axios request with timeout throw
 */
export default async function axiosRequest(config) {
  const { timeout } = config;

  let cancel;
  if(timeout) {
    console.log({ timeout });
    config.cancelToken = new CancelToken(c => cancel = c);
    setTimeout(() => {
      cancel('timeout cancel', { timeout });
    }, timeout);
  }

  return await axios(config);
}
```

**Comment by jkomyno** [comment] 2019-08-07 13:14
Checking for the `ECONNABORTED` error code worked for me:

```javascript
axios.post(...).then(response => {
  console.log('Success', response);
}).catch(error => {
  if (e.code === 'ECONNABORTED') {
    // the request has either been canceled due to a network timeout,
    // or because the device is offline
  }
});
```

**Comment by MaffooBristol** [comment] 2019-09-02 13:35
When using [cancel tokens](https://github.com/axios/axios#cancellation) you can check with the `axios.isCancel(error)` function:

```js
const source = axios.CancelToken.source();

try {
  setTimeout(() => {
    source.cancel('Cancelling after 10ms');
  }, 10);
  await axios.post('http://localhost:8080/foo', { foo: bar }, { cancelToken: source.token });
}
catch (error) {
  if (axios.isCancel(error)) {
    console.log('Request cancelled...');
  }
}

```

I don't know if this works for requests cancelled from elsewhere, but in case you're Googling for an answer to token cancellation this may help you.
