### ISSUE TITLE
Error: Interceptor not triggered

### ISSUE THREAD

**Issue by f-desroches** [mzabriskie/axios#995] opened 2017-07-09 14:17 UTC
Here is my interceptor
```
axios.interceptors.response.use((response) => {
  return response
}, function (error) {
  // Do something with response error
  if (error.response.status === 401) {
    auth.logout()
    router.replace('/login')
  }

  return Promise.reject(error)
})
```

During this call which returns a 401, the interceptor is not triggered. I can catch the reject() where I called method.
```
axios.get('/api/employees/')
      .then(response => {
        commit('SET_EMPLOYEE_LIST', response.data)
        resolve(response)
      })
      .catch(err => reject(err))
```

- axios version: v0.16.2
- Environment: chrome 59, windows 10

**Comment by Alexandre-Georges** [comment] 2017-07-13 17:21
I have had a similar issue, it seems like the axios instance is different when the interceptor is added and when a call is performed.

You also probably want to have a better handling of the 401 in the interceptor.

I found a workaround for the not triggered interceptor although it is probably a bug, I add the interceptor to the instance itself:
```
const instance = axios.create();
instance.interceptors.response.use((response) => {
  console.log(`response ${response}`);
  return response;
}, (error) => {
  console.log(`error ${error}`);
  return Promise.reject(error);
});
```

**Comment by rubennorte** [comment] 2017-08-12 11:50
This seems a duplicate of #993.

**Closed by rubennorte** 2017-08-12 11:50 UTC

**Comment by packytagliaferro** [comment] 2017-10-20 23:24
@f-desroches  any luck with this? I have this in my code:
```

window.axios.interceptors.response.use(function (response) {

    console.log(response);
    
    return response;

}, function (error) {

    if( error.response.status == 401 ){
        store.commit('logout');
    }

   return Promise.reject(error);

});

```
Which works on refresh, but on the first call I just get the `401` error. If I refresh and run it works???

**Comment by vijayst** [comment] 2018-09-05 13:17
@rubennorte This is not a duplicate of 993. For me, the global interceptor does not work!

I am using webpack for bundling. As startup code, I am setting up the interceptor. And then use

`import axios from 'axios';`

The interceptor is not called.

**Comment by hoangtrung99** [comment] 2019-08-19 14:43
I encountered a similar error, help me

**Comment by AlphaGeek** [comment] 2020-01-23 18:39
I have the same issue and I am attaching the interceptor to the instance that is returned by create() as suggested by Alexandre-Georges.  I am using 0.19.2.

**Comment by paddelboot** [comment] 2020-05-14 12:28
This is weird. In all the tutorials and SE answers, I see the interceptor being added to the axios instance. But this didn't work for me at all. Instead, I had to add it to the imported axios module *before* calling the `create()` method:

    import axios from 'axios';

    // Redirect if API return unauthorized
    axios.interceptors.response.use(function (response) {

    console.log( 'interceptor' );

    return response;
    }, function (error) {

    console.log( error );

    if (401 === error.response.status) {

        window.location = '/login';

    } else {
        return Promise.reject(error);
    }
    });

    const axiosInstance = axios.create({
    baseURL: `http://example.org/`,
    headers: {
        'Content-Type': 'application/json'
    },
    withCredentials: true
    });

    export default axiosInstance;
