### ISSUE TITLE
Can not override default header for an axios instance and default headers are shared for all instances

### ISSUE THREAD

**Issue by ghanjra** [mzabriskie/axios#466] opened 2016-10-03 23:01 UTC
I have setup like:
var api1= axios.create({
    baseURL: "www.myapi1.com"
});
api1.defaults.headers.post['Content-type'] = "application/x-www-form-urlencoded";

when i try to override the default with-in post request as below, it still sends default headers.
var config= {headers:{'Content-Type':'application/json'}};
api1.post("my/uri",{'key':'value'}, config); //still sends Content-Type="application/x-www-form-urlencoded"

Further, when i have multiple instances set up and one of them is having default header set, it is used by other instance as well. for example
var api1= axios.create({
    baseURL: "www.myapi1.com"
});
api1. defaults.headers.post['Content-type'] = "application/x-www-form-urlencoded";

var api2 = axios.create({
    baseURL: "www.myapi2.com"
}); 

var config= {headers:{'Content-Type':'application/json'}};
api2.post("my/uri",{'key':'value'}, config); // this will also send Content-Type="application/x-www-form-urlencoded"

**Comment by ghanjra** [comment] 2016-10-04 16:26
@mzabriskie any suggestion on this?

**Comment by rubennorte** [comment] 2016-10-04 21:09
This is a known bug. I'm closing this as duplicate of #385. Thanks for reporting.

**Closed by rubennorte** 2016-10-04 21:09 UTC

**Comment by ghanjra** [comment] 2016-10-05 22:54
@rubennorte Thanks.
