### ISSUE TITLE
cancelling cancelToken on request that is already finished gives error

### ISSUE THREAD

**Issue by vissermc** [mzabriskie/axios#482] opened 2016-10-14 08:09 UTC
there should be an easy mechanism to have 'overwrite' a request with a new one. Currently this is not possible. Also, it's not clear whether a cancelToken can be 'recycled', or whether a new one should be generated on every request

if (cancelToken) cancelToken.cancel();
cancelToken = axios.CancelToken.source();
axios.get(...

**Comment by nickuraltsev** [comment] 2016-10-14 16:02
- What error do you get? Also, could you please provide a code snippet that reproduces the issue? 
- I'm not sure I understand what you mean by "overwriting" requests.
- You should use different tokens for different requests unless you need to be able to cancel multiple requests as a group.

**Comment by vissermc** [comment] 2016-10-17 07:45
Code snippet:


 Uncaught (in promise) TypeError: Cannot read property 'abort' of null(…)onCanceled
if (config.cancelToken) {
	      // Handle cancellation
	      config.cancelToken.promise.then(function onCanceled(cancel) {
	        request.abort(); <-- here
	        reject(cancel);
	        // Clean up request
	        request = null;
	      });
	    }

**Comment by vissermc** [comment] 2016-10-17 07:46
When calling this function twice, I get:

Error: Uncaught (in promise) TypeError: Cannot read property 'abort' of null(…)onCanceled

 if (config.cancelToken) {
	      // Handle cancellation
	      config.cancelToken.promise.then(function onCanceled(cancel) {
	        request.abort(); <-- HERE
	        reject(cancel);
	        // Clean up request
	        request = null;
	      });
	    }

**Comment by TheCrow1213** [comment] 2016-10-17 20:19
Can confirm. Looks like lines `adapters/http.js:191` and `adapters/http.js:159` require null checks. For a method that sets the `request` var to null in several non-edge-cases, I'm surprised the check isn't in there.

**Comment by nickuraltsev** [comment] 2016-10-18 01:23
Fixed via 3fcf54f

**Closed by nickuraltsev** 2016-10-18 01:23 UTC

**Comment by TheCrow1213** [comment] 2016-10-18 17:25
Thanks @nickuraltsev :)

**Comment by jadelmir** [comment] 2018-03-14 07:35
I am getting an error while doing get request using axios 
TypeError: Cannot read property 'cancelToken' of undefined
what is that and how could deal with it
