### ISSUE TITLE
(node:24309) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'slice' of null (node:24309) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by EasonWang01** [mzabriskie/axios#544] opened 2016-11-21 00:21 UTC
when doing react.js project with isomorphic this message will appear when using axios on the server side.

**Comment by nickuraltsev** [comment] 2016-11-22 04:22
Duplicate of #506

**Closed by nickuraltsev** 2016-11-22 04:22 UTC
