### ISSUE TITLE
axios.delete - must specify 'data' object?

### ISSUE THREAD

**Issue by AkiraLaine** [mzabriskie/axios#736] opened 2017-03-03 05:00 UTC
When using the alias `axios.delete`, the payload doesn't get sent with the API call if you don't specify `data`.

You have to do:
```javascript
axios.delete(URL, {
 data: { foo: 'bar' }
})
```
instead of 
```javascript
axios.delete(URL, { foo: 'bar' })
```
According to [this](https://github.com/mzabriskie/axios#note), you shouldn't have to define `data`. I've been able to use other methods with payload without specifying `data`.

**Comment by charlesrochati** [comment] 2017-03-03 16:18
Nope, this won't work.

What you have to send to Axios is a [Request Config Object](https://github.com/mzabriskie/axios#request-config) and in this object you can find the `data` and `params` property. You will use them to send data to the server.

`axios.delete(URL, {params: {foo: 'bar'}})`


In a `delete request` you should use `params` instead of `data`, see the docs:

`  // "data" is the data to be sent as the request body`
`  // Only applicable for request methods 'PUT', 'POST', and 'PATCH'`
 ` // When no `transformRequest` is set, must be of one of the following types:`
 ` // - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams`
 ` // - Browser only: FormData, File, Blob`
  `// - Node only: Stream`
  

`data: {
    firstName: 'Fred'
  },`

**Comment by AkiraLaine** [comment] 2017-03-05 01:54
@charlesrochati I'm confused. `params` is to send query string parameters, that's not what I'm doing. 
As for what you quoted above, it says nothing about `delete`.

**Comment by charlesrochati** [comment] 2017-03-05 15:08
> params is to send query string parameters, that's not what I'm doing.

If you want to make a `axios.delete`, that's exactly what you have to do.

You don't use `axios.delete(URL, {`
 `data: { foo: 'bar' }` //Only applicable for request methods 'PUT', 'POST', and 'PATCH'
`})` 
for a delete request, you will use `axios.delete(URL, {`
 `params: { foo: 'bar' }` 
`})` 

You will send data as the request body ONLY WHEN you are using 'PUT', 'POST', and 'PATCH'.

I'm afraid you're using `axios.delete` just like a `axios.post ` or (`axios.post` or `axios.post`). When using `axios.delete`,  you'll send an `id` to a server, and the server itself will find a `resource` that matches that given `id`, only then it will be removed (or trigger some action, but the request is mapped as a `http delete`).

By using  `axios.delete(URL, {`
 `data: { foo: 'bar' }`
`})`  you're sending a `resource`, which makes no sense at all.

Take a look at the links below, you will have a better understanding:

http://stackoverflow.com/questions/12142652/what-is-the-usefulness-of-put-and-delete-http-request-methods

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html [Section 9.7]

**Comment by jcready** [comment] 2017-03-11 14:29
The HTTP DELETE method should not have a request body. DELETE is telling the origin server to remove the resource identified by the URI.

**Comment by AkiraLaine** [comment] 2017-03-12 03:20
In my case, we do pass a payload. But either way, if it works using `data`, it should work using the shorthand.

**Comment by charlesrochati** [comment] 2017-03-12 16:01
There is no shorthand for axios.delete:

axios.request(config)

axios.get(url[, config])

axios.delete(url[, config])

axios.head(url[, config])

axios.post(url[, data[, config]])

axios.put(url[, data[, config]])

axios.patch(url[, data[, config]])

**Comment by jcready** [comment] 2017-03-12 17:23
@AkiraLaine the specification also doesn't forbid sending request bodies for GET either. Should axios also allow you to use the short-hand notation for sending request bodies in GET requests as well?

**Comment by rubennorte** [comment] 2017-04-02 15:38
I'm closing the issue as it's the expected behaviour.

**Closed by rubennorte** 2017-04-02 15:38 UTC

**Comment by cggaurav** [comment] 2017-04-27 02:18
@rubennorte I think we should support `body` in `DEL` 
[HTTP 1.1](https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#page-23)
And for an example, [Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-request-scroll.html#_clear_scroll_api)

**Comment by jcready** [comment] 2017-04-27 11:37
@cggaurva it is supported.

```js
axios.delete('/some/uri', { body: 'my delete body' })
```

**Comment by aricsangchat** [comment] 2017-06-08 19:51
On a side note, On the server the id is showing up in req.query instead of req.params when using axios.delete('/some/uri', {params: { id: 1 } }) like this. Just wanted to throw that out there.

**Comment by jcready** [comment] 2017-06-09 13:04
@aricsangchat that's likely because you're using express which is not affiliated with axios at all. When express refers to `params` it is talking about dynamic values matched in the request path. When axios refers to `params` it is referring to query string parameters.

```js
// Express
router.get('/:foo/:bar', (req, res) => {
  res.json({
    query: req.query,
    params: req.params
  })
})
```

```js
// Axios
axios.get('/some/uri', { params: { id: 1 } })
.then((response) => console.log(response.data))
```

The output you'd get from running that would be:

```json
{
  "query": { "id": 1 },
  "params": {
    "foo": "some",
    "bar": "uri"
  }
}
```

**Comment by aricsangchat** [comment] 2017-06-27 15:55
@jcready Yup thats our setup.

**Comment by rudovjan** [comment] 2017-08-28 22:42
Where is written that delete cannot have a body (like post)?  It would be nice if axios supports this https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#page-23 

Thank you

**Comment by jcready** [comment] 2017-08-28 23:08
[It does support it.](#issuecomment-297689326)

**Comment by duhseekoh** [comment] 2017-10-16 18:34
FYI. Fair point's that DELETE should not have a body. However, sometimes you're stuck *having* to send a body when the api is out of your control. e.g.
https://auth0.com/docs/api/authorization-extension#remove-user-from-roles 👎

**Comment by jcready** [comment] 2017-10-16 18:49
@duhseekoh 

```js
const extension_url = 'mycompany.auth0.com'
const access_token = 'abc123'
const user_id = 12345
const role_id = 67890

axios.delete(`https://${extension_url}/users/${role_id}/roles`, {
  headers: {
    'Authorization': `Bearer ${access_token}`,
    'Content-Type': 'application/json'
  },
  body: JSON.stringify([
    user_id
  ])
})
```

**Comment by duhseekoh** [comment] 2017-10-16 18:52
@jcready - For sure and thanks for the example. Just wanted to add some reasoning for why a body may need to be passed when using axios.

**Comment by mrchief** [comment] 2017-11-14 19:32
@duhseekoh Maybe this will help: https://github.com/axios/axios/issues/897#issuecomment-343715381

**Comment by quinnliu** [comment] 2018-04-02 00:40
```
const response = await axios.delete('/api/matches/delete_match', {
		data: { matchInfo }
	});
```

I have it working with `data` but not working with `params` with version `"axios": "^0.17.1"`

**Comment by HanchengZhao** [comment] 2018-04-20 21:44
@quinnliu I think choosing to use `data` or `params` depends on how your backend handles the request.
* Using `data` is to put the payload inside request body, just as you do with `post`.
* Using `params` is to treat payloads as url params. Like if you send
```js
axios.delete(URL, {
 params: { foo: 'bar' }
})
```
it's same as sending request to `URL?foo=bar.`

**Comment by jrbytes** [comment] 2020-02-19 14:44
> > params is to send query string parameters, that's not what I'm doing.
> 
> If you want to make a `axios.delete`, that's exactly what you have to do.
> 
> You don't use `axios.delete(URL, {`
> `data: { foo: 'bar' }` //Only applicable for request methods 'PUT', 'POST', and 'PATCH'
> `})`
> for a delete request, you will use `axios.delete(URL, {`
> `params: { foo: 'bar' }`
> `})`
> 
> You will send data as the request body ONLY WHEN you are using 'PUT', 'POST', and 'PATCH'.
> 
> I'm afraid you're using `axios.delete` just like a `axios.post ` or (`axios.put` or `axios.patch`). When using `axios.delete`, you'll send an `id` to a server, and the server itself will find a `resource` that matches that given `id`, only then it will be removed (or trigger some action, but the request is mapped as a `http delete`).
> 
> By using `axios.delete(URL, {`
> `data: { foo: 'bar' }`
> `})` you're sending a `resource`, which makes no sense at all.
> 
> Take a look at the links below, you will have a better understanding:
> 
> http://stackoverflow.com/questions/12142652/what-is-the-usefulness-of-put-and-delete-http-request-methods
> 
> https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html [Section 9.7]

Thank you, 
My code:
`api.delete(`/projects/${idProjectTech}/techs`, {data: { name: data.name }})`

**Comment by jrbytes** [comment] 2020-02-19 14:52
Abstraction from axios in api. Params in data: name only
```
api.delete(`/projects/${idProjectTech}/techs`, {data: { name: data.name }})
